service: luna-api-main

frameworkVersion: '3'

custom:
  domain:
    dev: api.dev.luna.app.br
    prd: api.luna.app.br

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'prd'}
  # region: sa-east-1

functions:
  incomeHook:
    handler: bin/main
    events:
      - http:
          path: /
          method: any
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-certificate-creator