service: luna-api

frameworkVersion: "3"

custom:
  domain:
    dev: api.dev.luna.app.br
    prd: api.luna.app.br

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true
    basePath: v1

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'prd'}
  region: sa-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "*"

  environment:
    NODE_ENV: ${self:provider.stage}
    LUNA_INFRA_DB_NAME: luna-infra-${self:provider.stage}-db

functions:
  main:
    handler: bin/server
    events:
      - http:
          method: ANY
          path: "{proxy+}"
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-certificate-creator
