name: main-api

on:
  push:
    branches:
      - main

jobs:
  check-infra:
    name: deploy infra
    runs-on: ubuntu-latest
    env:
      STAGE: prd
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: check infra changes
        id: infra
        uses: tj-actions/changed-files@v35
        with:
          files: infra/**

      - name: check should deploy infra
        if: steps.infra.outputs.any_changed == 'true'
        run: |
          make deploy-infra

  build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    needs: check-infra
    env:
      STAGE: prd
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          make build
      - run: npm i serverless -g
      - run: npm install -D

      - name: Deploy to Serverless
        run: |
          make run
